# -*- coding: utf-8 -*-
"""Untitled154.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bektMX7RwYzkzvBp_VF5Aig8eGDMt4v
"""

print("Qadamova Zulayho")